trabalho-final/SisGAO/config/routes.rb
Rails.application.routes.draw do
  
  resources :devolucaos
  resources :retiradas
  resources :materials
  resources :unidade_medidas
  resources :funcionarios
  resources :fornecedors
  devise_for :users
  # # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'homes/index'  
  # get "home/index"
  root to: "retiradas#index"
end
# ruby ./bin/webpack-dev-server

trabalho-final/SisGAO/app/models/material.rb
class Material < ApplicationRecord
  belongs_to :UnidadeMedida
  belongs_to :Fornecedor

  def to_s
    self.nome
  end
end

trabalho-final/SisGAO/app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :set_material, only: [:show, :edit, :update, :destroy]

  # GET /materials
  # GET /materials.json
  def index
    @materials = Material.all
  end

  # GET /materials/1
  # GET /materials/1.json
  def show
  end

  # GET /materials/new
  def new
    @material = Material.new
  end

  # GET /materials/1/edit
  def edit
  end

  # POST /materials
  # POST /materials.json
  def create
    @material = Material.new(material_params)

    respond_to do |format|
      if @material.save
        format.html { redirect_to @material, notice: 'Material was successfully created.' }
        format.json { render :show, status: :created, location: @material }
      else
        format.html { render :new }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /materials/1
  # PATCH/PUT /materials/1.json
  def update
    respond_to do |format|
      if @material.update(material_params)
        format.html { redirect_to @material, notice: 'Material was successfully updated.' }
        format.json { render :show, status: :ok, location: @material }
      else
        format.html { render :edit }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materials/1
  # DELETE /materials/1.json
  def destroy
    @material.destroy
    respond_to do |format|
      format.html { redirect_to materials_url, notice: 'Material was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_material
      @material = Material.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def material_params
      params.require(:material).permit(:nome, :quantidadeMinima, :quantidade, :devolutivo, :UnidadeMedida_id, :Fornecedor_id)
    end
end

trabalho-final/SisGAO/app/helpers/materials_helper.rb
module MaterialsHelper
end

trabalho-final/SisGAO/app/views/materials/_form.html.erb
<%= simple_form_for @material do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nome %>
    <%= f.input :quantidadeMinima %>
    <%= f.input :quantidade %>
    <%= f.input :devolutivo %>
    <%= f.association :UnidadeMedida %>
    <%= f.association :Fornecedor %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, f.object.new_record? ? 'Criar Material' : 'Atualizar Material', class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>

trabalho-final/SisGAO/app/views/materials/edit.html.erb
<% content_for :title do %>
  Editando Material
<% end %>

<div class="page-header">
  <h1>Editando Material</h1>
  <div>
    <%= link_to @material, class: 'btn btn-info' do %>
      <%= icon 'fas', 'eye' %>
      Ver
    <% end %>
    <%= link_to materials_path, class: 'btn btn-outline-secondary' do %>
      <%= icon 'fas', 'bars' %>
      Voltar
    <% end %>
  </div>
</div>

<%= render 'form' %>

trabalho-final/SisGAO/app/views/materials/index.html.erb
<% content_for :title do %>
  Materials
<% end %>

<div class="page-header">
  <h1>Materials</h1>
  <%= link_to new_material_path, class: 'btn btn-primary' do %>
    <%= icon 'fas', 'plus' %>
    Novo Material
  <% end %>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Quantidademinima</th>
        <th>Quantidade</th>
        <th>Devolutivo</th>
        <th>Unidademedida</th>
        <th>Fornecedor</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @materials.each do |material| %>
        <tr>
          <td><%= material.nome %></td>
          <td><%= material.quantidadeMinima %></td>
          <td><%= material.quantidade %></td>
          <td><%= material.devolutivo %></td>
          <td><%= material.UnidadeMedida %></td>
          <td><%= material.Fornecedor %></td>
          <td>
            <%= link_to material, class: 'btn btn-info btn-sm' do %>
              <%= icon 'fas', 'eye', class: 'fa-fw' %>
            <% end %>
            <%= link_to edit_material_path(material), class: 'btn btn-success btn-sm' do %>
              <%= icon 'fas', 'edit', class: 'fa-fw' %>
            <% end %>
            <%= link_to material, method: :delete, data: { confirm: 'Você tem certeza?' }, class: 'btn btn-danger btn-sm' do %>
              <%= icon 'fas', 'times', class: 'fa-fw' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

trabalho-final/SisGAO/app/views/materials/new.html.erb
<% content_for :title do %>
  Novo Material
<% end %>

<div class="page-header">
  <h1>Novo Material</h1>
  <%= link_to materials_path, class: 'btn btn-outline-secondary' do %>
    <%= icon 'fas', 'bars' %>
    Voltar
  <% end %>
</div>

<%= render 'form' %>

trabalho-final/SisGAO/app/views/materials/show.html.erb
<% content_for :title do %>
  Detalhes de Material
<% end %>

<div class="page-header">
  <h1>Detalhes de Material</h1>
  <div>
    <%= link_to edit_material_path(@material), class: 'btn btn-success' do %>
      <%= icon 'fas', 'edit' %>
      Editar
    <% end %>
    <%= link_to materials_path, class: 'btn btn-outline-secondary' do %>
      <%= icon 'fas', 'bars' %>
      Voltar
    <% end %>
  </div>
</div>

<dl class="dl-horizontal">
  <dt>Nome:</dt>
  <dd><%= @material.nome %></dd>

  <dt>Quantidademinima:</dt>
  <dd><%= @material.quantidadeMinima %></dd>

  <dt>Quantidade:</dt>
  <dd><%= @material.quantidade %></dd>

  <dt>Devolutivo:</dt>
  <dd><%= @material.devolutivo %></dd>

  <dt>Unidademedida:</dt>
  <dd><%= @material.UnidadeMedida %></dd>

  <dt>Fornecedor:</dt>
  <dd><%= @material.Fornecedor %></dd>

</dl>