trabalho-final/SisGAO/config/routes.rb
Rails.application.routes.draw do
  
  resources :devolucaos
  resources :retiradas
  resources :materials
  resources :unidade_medidas
  resources :funcionarios
  resources :fornecedors
  devise_for :users
  # # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'homes/index'  
  # get "home/index"
  root to: "retiradas#index"
end
# ruby ./bin/webpack-dev-server

trabalho-final/SisGAO/app/models/retirada.rb
class Retirada < ApplicationRecord
  belongs_to :Material
  belongs_to :Funcionario
end

trabalho-final/SisGAO/app/controllers/retiradas_controller.rb
class RetiradasController < ApplicationController
  before_action :set_retirada, only: [:show, :edit, :update, :destroy]

  # GET /retiradas
  # GET /retiradas.json
  def index
    @retiradas = Retirada.all
  end

  # GET /retiradas/1
  # GET /retiradas/1.json
  def show
  end

  # GET /retiradas/new
  def new
    @retirada = Retirada.new
  end

  # GET /retiradas/1/edit
  def edit
  end

  # POST /retiradas
  # POST /retiradas.json
  def create
    @retirada = Retirada.new(retirada_params)

    respond_to do |format|
      if @retirada.save
        format.html { redirect_to @retirada, notice: 'Retirada was successfully created.' }
        format.json { render :show, status: :created, location: @retirada }
      else
        format.html { render :new }
        format.json { render json: @retirada.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /retiradas/1
  # PATCH/PUT /retiradas/1.json
  def update
    respond_to do |format|
      if @retirada.update(retirada_params)
        format.html { redirect_to @retirada, notice: 'Retirada was successfully updated.' }
        format.json { render :show, status: :ok, location: @retirada }
      else
        format.html { render :edit }
        format.json { render json: @retirada.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /retiradas/1
  # DELETE /retiradas/1.json
  def destroy
    @retirada.destroy
    respond_to do |format|
      format.html { redirect_to retiradas_url, notice: 'Retirada was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_retirada
      @retirada = Retirada.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def retirada_params
      params.require(:retirada).permit(:quantidade, :Material_id, :Funcionario_id)
    end
end

trabalho-final/SisGAO/app/helpers/retiradas_helper.rb
module RetiradasHelper
end

trabalho-final/SisGAO/app/views/retiradas/_form.html.erb
<%= simple_form_for @retirada do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :quantidade %>
    <%= f.association :Material %>
    <%= f.association :Funcionario %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, f.object.new_record? ? 'Criar Retirada' : 'Atualizar Retirada', class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>

trabalho-final/SisGAO/app/views/retiradas/edit.html.erb
<% content_for :title do %>
  Editando Retirada
<% end %>

<div class="page-header">
  <h1>Editando Retirada</h1>
  <div>
    <%= link_to @retirada, class: 'btn btn-info' do %>
      <%= icon 'fas', 'eye' %>
      Ver
    <% end %>
    <%= link_to retiradas_path, class: 'btn btn-outline-secondary' do %>
      <%= icon 'fas', 'bars' %>
      Voltar
    <% end %>
  </div>
</div>

<%= render 'form' %>

trabalho-final/SisGAO/app/views/retiradas/index.html.erb
<% content_for :title do %>
  Retiradas
<% end %>

<div class="page-header">
  <h1>Retiradas</h1>
  <%= link_to new_retirada_path, class: 'btn btn-primary' do %>
    <%= icon 'fas', 'plus' %>
    Novo Retirada
  <% end %>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Quantidade</th>
        <th>Material</th>
        <th>Funcionario</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @retiradas.each do |retirada| %>
        <tr>
          <td><%= retirada.quantidade %></td>
          <td><%= retirada.Material %></td>
          <td><%= retirada.Funcionario %></td>
          <td>
            <%= link_to retirada, class: 'btn btn-info btn-sm' do %>
              <%= icon 'fas', 'eye', class: 'fa-fw' %>
            <% end %>
            <%= link_to edit_retirada_path(retirada), class: 'btn btn-success btn-sm' do %>
              <%= icon 'fas', 'edit', class: 'fa-fw' %>
            <% end %>
            <%= link_to retirada, method: :delete, data: { confirm: 'Você tem certeza?' }, class: 'btn btn-danger btn-sm' do %>
              <%= icon 'fas', 'times', class: 'fa-fw' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

trabalho-final/SisGAO/app/views/retiradas/new.html.erb
<% content_for :title do %>
  Novo Retirada
<% end %>

<div class="page-header">
  <h1>Novo Retirada</h1>
  <%= link_to retiradas_path, class: 'btn btn-outline-secondary' do %>
    <%= icon 'fas', 'bars' %>
    Voltar
  <% end %>
</div>

<%= render 'form' %>

trabalho-final/SisGAO/app/views/retiradas/show.html.erb
<% content_for :title do %>
  Detalhes de Retirada
<% end %>

<div class="page-header">
  <h1>Detalhes de Retirada</h1>
  <div>
    <%= link_to edit_retirada_path(@retirada), class: 'btn btn-success' do %>
      <%= icon 'fas', 'edit' %>
      Editar
    <% end %>
    <%= link_to retiradas_path, class: 'btn btn-outline-secondary' do %>
      <%= icon 'fas', 'bars' %>
      Voltar
    <% end %>
  </div>
</div>

<dl class="dl-horizontal">
  <dt>Quantidade:</dt>
  <dd><%= @retirada.quantidade %></dd>

  <dt>Material:</dt>
  <dd><%= @retirada.Material %></dd>

  <dt>Funcionario:</dt>
  <dd><%= @retirada.Funcionario %></dd>

</dl>