trabalho-final/SisGAO/config/routes.rb
Rails.application.routes.draw do
  
  resources :devolucaos
  resources :retiradas
  resources :materials
  resources :unidade_medidas
  resources :funcionarios
  resources :fornecedors
  devise_for :users
  # # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'homes/index'  
  # get "home/index"
  root to: "retiradas#index"
end
# ruby ./bin/webpack-dev-server

trabalho-final/SisGAO/app/models/unidade_medida.rb
class UnidadeMedida < ApplicationRecord
    def to_s
        self.nome
    end
end

trabalho-final/SisGAO/app/controllers/unidade_medidas_controller.rb
class UnidadeMedidasController < ApplicationController
  before_action :set_unidade_medida, only: [:show, :edit, :update, :destroy]

  # GET /unidade_medidas
  # GET /unidade_medidas.json
  def index
    @unidade_medidas = UnidadeMedida.all
  end

  # GET /unidade_medidas/1
  # GET /unidade_medidas/1.json
  def show
  end

  # GET /unidade_medidas/new
  def new
    @unidade_medida = UnidadeMedida.new
  end

  # GET /unidade_medidas/1/edit
  def edit
  end

  # POST /unidade_medidas
  # POST /unidade_medidas.json
  def create
    @unidade_medida = UnidadeMedida.new(unidade_medida_params)

    respond_to do |format|
      if @unidade_medida.save
        format.html { redirect_to @unidade_medida, notice: 'Unidade medida was successfully created.' }
        format.json { render :show, status: :created, location: @unidade_medida }
      else
        format.html { render :new }
        format.json { render json: @unidade_medida.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /unidade_medidas/1
  # PATCH/PUT /unidade_medidas/1.json
  def update
    respond_to do |format|
      if @unidade_medida.update(unidade_medida_params)
        format.html { redirect_to @unidade_medida, notice: 'Unidade medida was successfully updated.' }
        format.json { render :show, status: :ok, location: @unidade_medida }
      else
        format.html { render :edit }
        format.json { render json: @unidade_medida.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unidade_medidas/1
  # DELETE /unidade_medidas/1.json
  def destroy
    @unidade_medida.destroy
    respond_to do |format|
      format.html { redirect_to unidade_medidas_url, notice: 'Unidade medida was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unidade_medida
      @unidade_medida = UnidadeMedida.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unidade_medida_params
      params.require(:unidade_medida).permit(:nome)
    end
end

trabalho-final/SisGAO/app/helpers/unidade_medidas_helper.rb
module UnidadeMedidasHelper
end

trabalho-final/SisGAO/app/views/unidade_medidas/_form.html.erb
<%= simple_form_for @unidade_medida do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nome %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, f.object.new_record? ? 'Criar Unidade medida' : 'Atualizar Unidade medida', class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>

trabalho-final/SisGAO/app/views/unidade_medidas/edit.html.erb
<% content_for :title do %>
  Editando Unidade medida
<% end %>

<div class="page-header">
  <h1>Editando Unidade medida</h1>
  <div>
    <%= link_to @unidade_medida, class: 'btn btn-info' do %>
      <%= icon 'fas', 'eye' %>
      Ver
    <% end %>
    <%= link_to unidade_medidas_path, class: 'btn btn-outline-secondary' do %>
      <%= icon 'fas', 'bars' %>
      Voltar
    <% end %>
  </div>
</div>

<%= render 'form' %>

trabalho-final/SisGAO/app/views/unidade_medidas/index.html.erb
<% content_for :title do %>
  Unidade medidas
<% end %>

<div class="page-header">
  <h1>Unidade medidas</h1>
  <%= link_to new_unidade_medida_path, class: 'btn btn-primary' do %>
    <%= icon 'fas', 'plus' %>
    Novo Unidade medida
  <% end %>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Nome</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @unidade_medidas.each do |unidade_medida| %>
        <tr>
          <td><%= unidade_medida.nome %></td>
          <td>
            <%= link_to unidade_medida, class: 'btn btn-info btn-sm' do %>
              <%= icon 'fas', 'eye', class: 'fa-fw' %>
            <% end %>
            <%= link_to edit_unidade_medida_path(unidade_medida), class: 'btn btn-success btn-sm' do %>
              <%= icon 'fas', 'edit', class: 'fa-fw' %>
            <% end %>
            <%= link_to unidade_medida, method: :delete, data: { confirm: 'Você tem certeza?' }, class: 'btn btn-danger btn-sm' do %>
              <%= icon 'fas', 'times', class: 'fa-fw' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

trabalho-final/SisGAO/app/views/unidade_medidas/new.html.erb
<% content_for :title do %>
  Novo Unidade medida
<% end %>

<div class="page-header">
  <h1>Novo Unidade medida</h1>
  <%= link_to unidade_medidas_path, class: 'btn btn-outline-secondary' do %>
    <%= icon 'fas', 'bars' %>
    Voltar
  <% end %>
</div>

<%= render 'form' %>

trabalho-final/SisGAO/app/views/unidade_medidas/show.html.erb
<% content_for :title do %>
  Detalhes de Unidade medida
<% end %>

<div class="page-header">
  <h1>Detalhes de Unidade medida</h1>
  <div>
    <%= link_to edit_unidade_medida_path(@unidade_medida), class: 'btn btn-success' do %>
      <%= icon 'fas', 'edit' %>
      Editar
    <% end %>
    <%= link_to unidade_medidas_path, class: 'btn btn-outline-secondary' do %>
      <%= icon 'fas', 'bars' %>
      Voltar
    <% end %>
  </div>
</div>

<dl class="dl-horizontal">
  <dt>Nome:</dt>
  <dd><%= @unidade_medida.nome %></dd>

</dl>