trabalho-final/SisGAO/config/routes.rb
Rails.application.routes.draw do
  
  resources :devolucaos
  resources :retiradas
  resources :materials
  resources :unidade_medidas
  resources :funcionarios
  resources :fornecedors
  devise_for :users
  # # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'homes/index'  
  # get "home/index"
  root to: "retiradas#index"
end
# ruby ./bin/webpack-dev-server

trabalho-final/SisGAO/app/models/funcionario.rb
class Funcionario < ApplicationRecord
    enum cargo: [:admin, :almoxarife, :comum]
    belongs_to :user
end

trabalho-final/SisGAO/app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  before_action :set_funcionario, only: [:show, :edit, :update, :destroy]

  # GET /funcionarios
  # GET /funcionarios.json
  def index
    @funcionarios = Funcionario.all
  end

  # GET /funcionarios/1
  # GET /funcionarios/1.json
  def show
  end

  # GET /funcionarios/new
  def new
    @funcionario = Funcionario.new
    @cargos = Funcionario.cargos.keys
    @cargos = @cargos - [:admin.to_s] unless current_user.funcionario.admin?
  end

  # GET /funcionarios/1/edit
  def edit
  end

  # POST /funcionarios
  # POST /funcionarios.json
  def create
    @funcionario = Funcionario.new(funcionario_params)

    respond_to do |format|
      if @funcionario.save
        format.html { redirect_to @funcionario, notice: 'Funcionario was successfully created.' }
        format.json { render :show, status: :created, location: @funcionario }
      else
        format.html { render :new }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funcionarios/1
  # PATCH/PUT /funcionarios/1.json
  def update
    respond_to do |format|
      if @funcionario.update(funcionario_params)
        format.html { redirect_to @funcionario, notice: 'Funcionario was successfully updated.' }
        format.json { render :show, status: :ok, location: @funcionario }
      else
        format.html { render :edit }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcionarios/1
  # DELETE /funcionarios/1.json
  def destroy
    @funcionario.destroy
    respond_to do |format|
      format.html { redirect_to funcionarios_url, notice: 'Funcionario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funcionario
      @funcionario = Funcionario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def funcionario_params
      params.require(:funcionario).permit(:matricula, :nome, :setor, :cargo)
    end
end

trabalho-final/SisGAO/app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

trabalho-final/SisGAO/app/views/funcionarios/_form.html.erb
<%= simple_form_for @funcionario do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :matricula %>
    <%= f.input :nome %>
    <%= f.input :setor %>
    <%= f.input :cargo, collection: @cargos %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, f.object.new_record? ? 'Criar Funcionario' : 'Atualizar Funcionario', class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>

trabalho-final/SisGAO/app/views/funcionarios/edit.html.erb
<% content_for :title do %>
  Editando Funcionario
<% end %>

<div class="page-header">
  <h1>Editando Funcionario</h1>
  <div>
    <%= link_to @funcionario, class: 'btn btn-info' do %>
      <%= icon 'fas', 'eye' %>
      Ver
    <% end %>
    <%= link_to funcionarios_path, class: 'btn btn-outline-secondary' do %>
      <%= icon 'fas', 'bars' %>
      Voltar
    <% end %>
  </div>
</div>

<%= render 'form' %>

trabalho-final/SisGAO/app/views/funcionarios/index.html.erb
<% content_for :title do %>
  Funcionarios
<% end %>

<div class="page-header">
  <h1>Funcionarios</h1>
  <%= link_to new_funcionario_path, class: 'btn btn-primary' do %>
    <%= icon 'fas', 'plus' %>
    Novo Funcionario
  <% end %>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Matricula</th>
        <th>Nome</th>
        <th>Setor</th>
        <th>Cargo</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @funcionarios.each do |funcionario| %>
        <tr>
          <td><%= funcionario.matricula %></td>
          <td><%= funcionario.nome %></td>
          <td><%= funcionario.setor %></td>
          <td><%= funcionario.cargo %></td>
          <td>
            <%= link_to funcionario, class: 'btn btn-info btn-sm' do %>
              <%= icon 'fas', 'eye', class: 'fa-fw' %>
            <% end %>
            <%= link_to edit_funcionario_path(funcionario), class: 'btn btn-success btn-sm' do %>
              <%= icon 'fas', 'edit', class: 'fa-fw' %>
            <% end %>
            <%= link_to funcionario, method: :delete, data: { confirm: 'Você tem certeza?' }, class: 'btn btn-danger btn-sm' do %>
              <%= icon 'fas', 'times', class: 'fa-fw' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

trabalho-final/SisGAO/app/views/funcionarios/new.html.erb
<% content_for :title do %>
  Novo Funcionario
<% end %>

<div class="page-header">
  <h1>Novo Funcionario</h1>
  <%= link_to funcionarios_path, class: 'btn btn-outline-secondary' do %>
    <%= icon 'fas', 'bars' %>
    Voltar
  <% end %>
</div>

<%= render 'form' %>

trabalho-final/SisGAO/app/views/funcionarios/show.html.erb
<% content_for :title do %>
  Detalhes de Funcionario
<% end %>

<div class="page-header">
  <h1>Detalhes de Funcionario</h1>
  <div>
    <%= link_to edit_funcionario_path(@funcionario), class: 'btn btn-success' do %>
      <%= icon 'fas', 'edit' %>
      Editar
    <% end %>
    <%= link_to funcionarios_path, class: 'btn btn-outline-secondary' do %>
      <%= icon 'fas', 'bars' %>
      Voltar
    <% end %>
  </div>
</div>

<dl class="dl-horizontal">
  <dt>Matricula:</dt>
  <dd><%= @funcionario.matricula %></dd>

  <dt>Nome:</dt>
  <dd><%= @funcionario.nome %></dd>

  <dt>Setor:</dt>
  <dd><%= @funcionario.setor %></dd>

  <dt>Cargo:</dt>
  <dd><%= @funcionario.cargo %></dd>

</dl>